<a href="https://colab.research.google.com/github/MayankGoel28/d2l-exercises/blob/main/2_1_data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [10]:
x = torch.arange(10, dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
x.numel()

10

In [12]:
x.shape

torch.Size([10])

In [14]:
X = x.reshape(5, 2)
X

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [15]:
torch.zeros((2, 3, 4, 2))

tensor([[[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]]])

In [16]:
torch.ones((2, 1, 2))

tensor([[[1., 1.]],

        [[1., 1.]]])

In [17]:
torch.randn(3, 4, 2)

tensor([[[-0.3366,  1.5186],
         [ 0.2773, -0.4749],
         [-0.6946, -1.8924],
         [ 0.5493, -2.2593]],

        [[ 0.5988,  0.0419],
         [ 0.0272,  0.8784],
         [-1.2882, -1.4221],
         [-0.9040,  0.1577]],

        [[-1.0948, -0.1863],
         [-0.9354,  0.4698],
         [-0.9197, -1.1327],
         [ 0.2089,  2.1312]]])

In [18]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [19]:
X[-2], X[1:3]

(tensor([6., 7.]),
 tensor([[2., 3.],
         [4., 5.]]))

In [21]:
X[1, 1] = 17
X

tensor([[ 0.,  1.],
        [ 2., 17.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.]])

In [27]:
X[:, 1] = 10
X

tensor([[11., 10.],
        [11., 10.],
        [ 4., 10.],
        [ 6., 10.],
        [ 8., 10.]])

In [28]:
torch.exp(x)

tensor([5.9874e+04, 2.2026e+04, 5.9874e+04, 2.2026e+04, 5.4598e+01, 2.2026e+04,
        4.0343e+02, 2.2026e+04, 2.9810e+03, 2.2026e+04])

In [29]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [33]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=-2)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]))

In [34]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [35]:
X.sum()

tensor(66.)

https://pytorch.org/docs/stable/notes/broadcasting.html

In [45]:
a = torch.arange(12).reshape((3, 2, 2))
b = torch.arange(4).reshape((1, 2, 2))
a, b

(tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]),
 tensor([[[0, 1],
          [2, 3]]]))

In [46]:
a + b

tensor([[[ 0,  2],
         [ 4,  6]],

        [[ 4,  6],
         [ 8, 10]],

        [[ 8, 10],
         [12, 14]]])

In [47]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [48]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 133966401001840
id(Z): 133966401001840


In [49]:
before = id(X)
X += Y
id(X) == before

True

In [50]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [51]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)