<a href="https://colab.research.google.com/github/MayankGoel28/d2l-exercises/blob/main/2_3_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

1. When we take a transpose of a matrix, every element $A_{ij}$ is changed to $A_{ji}$, so when we take the transpose again, $A_{ji}$ becomes $A_{ij}$. As every element in the matrix is the same as the original matrix, the two matrices are equivalent

2. For the LHS: Each element can be represented as $A_{ji} + B_{ji}$. \
    For the RHS: Each element is initially $A_{ij} + B_{ij}$, which let's say is equal to $C_{ij}$. Then after transposing, we get $C_{ji}$, which is originally equivalent to $A_{ji} + B_{ji}$, thus proving them same.

3. To prove, the matrix $A+A^T$ is equal to $(A+A^T)^T$ \
Using (1) - To calculate $(A^T)^T$ and (2), RHS becomes equal to $A^T + A$, and as addition of matrix is commutative, LHS = RHS


4. Without writing code - the guess is 2.

In [2]:
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

5. Len(X) should always correspond to the 0th axis

In [3]:
len(X) == X.shape[0]

True

6.

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

6.

In [5]:
A / A.sum(axis=1, keepdim=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

7. The Manhattan distance between two points can be calculated by $|x_2 - x_1|+ |y_2 - y_1|$. You can't travel diagonally.

8.

In [6]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [7]:
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

9.



In [8]:
import numpy as np

In [9]:
X = torch.arange(60).reshape(3, 4, 5)

In [10]:
np.linalg.norm(X)

264.9716966017314

10. $(AB)C$ stores the intermediate result with dimensions $\mathbb{R}^{2^{10} \times 2^5}$, whereas $A(BC)$ stores the intermediate with dimensions $\mathbb{R}^{2^{16} \times 2^{14}}$. Thus, a larger intemediate result is stored in the latter, and this affects the memory footprint, as well as speed.

11. Pytorch treats $C^T$ as a view rather than by assigning new memory. Thus, there are no differences between calculating $AB$ and $AC^T$. However cloning does take up extra space.

In [11]:
A = torch.rand(100, 200)
B = torch.rand(100, 200)
C = torch.rand(100, 200)

In [12]:
X = torch.stack((A, B, C), dim=0)

In [13]:
X.shape

torch.Size([3, 100, 200])

In [14]:
B_2 = X[1, :, :]

In [15]:
B_2 == B

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])